- name: copy epel repository
  copy:
      src: epel.repo
      dest: /etc/yum.repos.d/epel.repo
- name: copy nginx repository
  copy:
      src: nginx.repo
      dest: /etc/yum.repos.d/nginx.repo
- name: install the latest version of nginx
  yum: name=nginx state=present
- name: copy nginx configuration file
  copy:
      src: default.conf
      dest: /etc/nginx/conf.d/default.conf
- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
    
