- name: Install Java Jdk
  hosts: nodes
  remote_user: root

  roles:
    - java

- name: Install Elasticsearch
  hosts: nodes
  become: yes

  roles:
    - elasticsearch
    
- hosts: nodes
  remote_user: root
  become: yes
  vars_prompt:
     - name: minheap
       prompt: enter minimum heap
       private: no
     - name: maxheap
       prompt: enter maximum heap
       private: no
  tasks:
    - name: HMS
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: "-Xms1g"
        line: "-Xms{{ minheap }}g"
        state: present
        backup: yes
   - name: HMX
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: "-Xms1g"
        line: "-Xms{{ maxheap }}g"
        state: present
        backup: yes
        
- name: Install Logstash
  hosts: nodes
  remote_user: root

  roles:
    - logstash

- name: Install Kibana
  hosts: nodes
  remote_user: root

  roles:
    - kibana

- name: Install Nginx
  hosts: nodes
  remote_user: root

  roles:
    - nginx

- name: Install Filebeat
  hosts: nodes
  remote_user: root

  roles:
    - filebeat
